# Nama proyek Anda di Cloudflare Pages
name = "video-saya"

# Konfigurasi untuk Pages Functions
[pages_build_output]
# Folder output build Next.js. Ini akan selalu menjadi ".next/static" dan ".next/server"
functions_directory = ".next/server"
static_directory = ".next/static"

# Pengaturan tambahan untuk Pages Functions
[pages_build_output.functions_settings]
# Gunakan kompatibilitas Node.js untuk memastikan modul Next.js berfungsi
nodejs_compat = true

# Konfigurasi binding D1
[[d1_databases]]
binding = "DB"
database_name = "nama-database-anda" # Ganti dengan nama database D1 Anda
database_id = "your-database-id" # Ganti dengan ID database Anda
